image: node:latest

before_script:
  - node -v
  - npm -v
  - npm install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - node_modules/.bin/istanbul cover node_modules/mocha/bin/_mocha -- -R spec
  only:
    - master
