before_script:
  - node -v
  - npm -v
  - npm install

stages:
  - test
  - deploy

coverLatest:
  image: node:latest
  stage: test
  script:
    - npm run cover
  only:
    - master

cover6:
  image: node:6.0.0
  stage: test
  script:
    - npm run cover
  only:
    - master

lint:
  image: node:latest
  stage: test
  script:
    - npm run lint
  only:
    - master

pages:
  image: node:latest
  stage: deploy
  script:
    - npm run docs
  artifacts:
    paths:
      - public
  only:
    - master