language: node_js
node_js:
    - "6"
    - "6.1"
    - "6.2"
    - "6.3"
    - "6.4"
    - "6.5"
    - "6.6"
    - "6.7"
before_install:
    - npm install -g mocha
    - npm install -g codeclimate-test-reporter
    - npm install -g istanbul
install:
    - npm install
before_script:
    - istanbul cover _mocha -- -R spec
after_success:
    - CODECLIMATE_REPO_TOKEN=$CLIMATE codeclimate-test-reporter < coverage/lcov.info
addons:
    code_climate:
        repo_token: CLIMATE
