language: node_js
node_js:
    - "6"
    - "6.9.1"
before_install:
    - npm install -g mocha
    - npm install -g codeclimate-test-reporter
    - npm install -g istanbul
install:
    - npm install
before_script:
    - istanbul cover _mocha -- -R spec
after_success:
    - CODECLIMATE_REPO_TOKEN=$CLIMATE codeclimate-test-reporter < coverage/lcov.info
addons:
    code_climate:
        repo_token: $CLIMATE
