site_name: vndbjs
repo_url: https://github.com/arbauman/vndbjs
google_analytics: ['UA-86345129-2', 'auto']
theme: readthedocs
pages:
  - Home: index.md
  - Example: example.md
  - Functions: functions.md
  - Reference:
    - Get: get.md
  - Contribution: contribution.md
